# Autogenerated by devscripts/update-version.py

__version__ = '2026.10.08.1'

RELEASE_GIT_HEAD = '11e34b173a2d122edd579026015c3e9c697df91d'

VARIANT = 'stepik-py37'

UPDATE_HINT = 'Update this fork through the Stepik dependency pin.'

CHANNEL = 'stable'

ORIGIN = 'StepikOrg/yt-dlp'

_pkg_version = '2026.10.08.1'
