# Autogenerated by devscripts/update-version.py

__version__ = '2026.10.07'

RELEASE_GIT_HEAD = '51bab8a0116f4d8004c315706d809782607d5847'

VARIANT = 'stepik-py37'

UPDATE_HINT = 'Update this fork through the Stepik dependency pin.'

CHANNEL = 'stable'

ORIGIN = 'StepikOrg/yt-dlp'

_pkg_version = '2026.10.07'
