# Autogenerated by devscripts/update-version.py

__version__ = '2026.10.08'

RELEASE_GIT_HEAD = '12046cc4d35dc918628708c67062a9066a69e5af'

VARIANT = 'stepik-py37'

UPDATE_HINT = 'Update this fork through the Stepik dependency pin.'

CHANNEL = 'stable'

ORIGIN = 'StepikOrg/yt-dlp'

_pkg_version = '2026.10.08'
